# Generated by Django 3.0.7 on 2023-04-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20230412_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(choices=[('Carlow', 'N0'), ('Cavan', 'N1'), ('Clare', 'N2'), ('Cork', 'N3'), ('Donegal', 'N4'), ('Dublin', 'N5'), ('Galway', 'N6'), ('Kerry', 'N8'), ('Kildare', 'N9'), ('Kilkenny', 'NA'), ('Laois', 'NG'), ('Leitrim', 'NI'), ('Limerick', 'NK'), ('Longford', 'NL'), ('Louth', 'NM'), ('Mayo', 'NN'), ('Meath', 'NO'), ('Monaghan', 'NP'), ('Offaly', 'NQ'), ('Roscommon', 'NR'), ('Sligo', 'NW'), ('Tipperary NR', 'NX'), ('Tipperary SR', 'NY'), ('Waterford', 'NZ'), ('Westmeath', '10'), ('Wexford', '11'), ('Wicklow', '12')], max_length=100),
        ),
    ]
